dist: trusty
sudo: required
cache: cargo

before_install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get -qq update
  - sudo apt-get install -y libc6:i386 zlib1g:i386

script:
  - make build
  
deploy:
  provider: releases
  api-key: 1e53cd86acdf667cd4875403534cb6757959e1c2
  file: e3372h-kmods/build-dir/kernel-build/drivers/net/*
  skip_cleanup: true
  draft: true
